# Generated by Django 4.2.5 on 2023-09-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
